/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: "class",
    content: [
        "./index.html",
        "./sections/**/*.html",
    ],
    theme: {
        extend: {
            colors: {
                "on-surface": "#1c1c18",
                "on-surface-variant": "#444748",
                "secondary-fixed-dim": "#ffb59d",
                "primary-container": "#1c1c1c",
                "on-primary": "#ffffff",
                "inverse-surface": "#31312c",
                "tertiary-fixed": "#d3e4ff",
                "surface-container": "#f1eee7",
                "on-error-container": "#93000a",
                "outline": "#747878",
                "surface-tint": "#5f5e5e",
                "secondary-container": "#457b9d",
                "on-primary-fixed": "#1b1b1b",
                "primary-fixed-dim": "#c8c6c5",
                "on-primary-container": "#858484",
                "surface-container-high": "#ebe8e1",
                "secondary": "#d9381e",
                "tertiary-container": "#001d39",
                "surface": "#ffffff",
                "surface-container-low": "#f6f3ec",
                "tertiary-fixed-dim": "#aac9f4",
                "on-secondary-container": "#f1eee7",
                "background": "#f8f9fa",
                "on-tertiary": "#ffffff",
                "primary": "#0e3b64",
                "error": "#ba1a1a",
                "inverse-primary": "#c8c6c5",
                "on-background": "#1c1c18",
                "on-secondary-fixed": "#161c1f",
                "on-tertiary-fixed-variant": "#29486d",
                "surface-dim": "#dcdad3",
                "on-error": "#ffffff",
                "primary-fixed": "#e5e2e1",
                "surface-bright": "#fcf9f2",
                "on-primary-fixed-variant": "#474746",
                "tertiary": "#000105",
                "outline-variant": "#c4c7c7",
                "surface-variant": "#e5e2db",
                "surface-container-lowest": "#ffffff",
                "on-secondary-fixed-variant": "#1d3557",
                "on-tertiary-fixed": "#001c38",
                "secondary-fixed": "#457b9d",
                "on-secondary": "#ffffff",
                "error-container": "#ffdad6",
                "on-tertiary-container": "#6886af",
                "surface-container-highest": "#e5e2db",
                "inverse-on-surface": "#f3f0e9",
            },
            borderRadius: {
                DEFAULT: "0px",
                lg: "0px",
                xl: "0px",
                full: "0px",
            },
            spacing: {
                md: "32px",
                lg: "64px",
                max_width: "1280px",
                xl: "128px",
                base: "8px",
                xs: "4px",
                sm: "16px",
            },
            fontFamily: {
                "label-mono": ["DM Mono"],
                h3: ["Playfair Display"],
                "h2-mobile": ["Playfair Display"],
                "body-lg": ["DM Sans"],
                "body-md": ["DM Sans"],
                h1: ["Playfair Display"],
                "h1-mobile": ["Playfair Display"],
                h2: ["Playfair Display"],
            },
            fontSize: {
                "label-mono": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
                h3: ["24px", { lineHeight: "1.3", fontWeight: "700" }],
                "h2-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
                "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
                "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
                h1: ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
                "h1-mobile": ["40px", { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "700" }],
                h2: ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
            },
        },
    },
    plugins: [
        require("@tailwindcss/forms"),
    ],
};
